# Generated by Django 2.2 on 2019-07-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnimalType', models.CharField(choices=[('sow', 'SOW'), ('cow', 'COW'), ('sheep', 'SHEEP')], default='sow', max_length=3)),
                ('TagNumber', models.CharField(max_length=255)),
                ('disease', models.CharField(choices=[('diarrhea', 'DIARRHEA'), ('bedsore', 'BEDSORE')], default='diarrhea', max_length=2)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
