# Generated by Django 2.2 on 2019-07-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='TreatmentStatus',
            field=models.CharField(choices=[('ok', 'Ok'), ('warning', 'Warning'), ('warning', 'Warning'), ('critical', 'Critical')], default='sow', max_length=255),
        ),
        migrations.AlterField(
            model_name='journal',
            name='AnimalType',
            field=models.CharField(choices=[('sow', 'Sow'), ('cow', 'Cow'), ('sheep', 'Sheep')], default='sow', max_length=255),
        ),
        migrations.AlterField(
            model_name='journal',
            name='disease',
            field=models.CharField(choices=[('diarrhea', 'DIARRHEA'), ('bedsore', 'BEDSORE')], default='diarrhea', max_length=255),
        ),
    ]
