# Generated by Django 2.2 on 2019-07-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='Location',
            field=models.CharField(default='Optional to set location', max_length=255),
        ),
    ]
