# Generated by Django 2.2 on 2019-07-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_journal_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='journals.Journal'),
        ),
    ]
